# Fungsi: Membuat container PostgreSQL (database) di Kubernetes.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        image: postgres:16          # → Pakai PostgreSQL versi 16.
        ports:
        - containerPort: 5432
        env:                        # → Setting username/password database (admin/admin123).
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin123
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:               # Simpan data di mountPath (agar tidak hilang saat restart).
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc